name: Build
on:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - master

env:
  DOCKER_REPOSITORY: acouvreur/mongo-backup-local
  CI: true

jobs:
  build:
    name: Build Docker artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login
        if: github.ref == 'refs/heads/master'
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
  
      - name: build the image
        if: github.ref == 'refs/heads/master'
        run: docker buildx build --push --tag ${{ env.DOCKER_REPOSITORY }}:latest --platform linux/amd64,linux/arm64/v8 .